name: CI

on:
  push:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "20"
          - "22"
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install packages from NPM
        run: npm ci
      - name: Run unit tests
        run: npm run test -- --verbose --coverage
      - name: Verify production build
        run: npm run build
