name: Test

on:
  push:
    paths:
      - ".github/workflows/**"
      - ".npmrc"
      - ".releaserc.json"
      - "jest.config.ts"
      - "package-lock.json"
      - "package.json"
      - "README.md"
      - "scripts/**"
      - "source/**"
      - "tsconfig.json"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Action | Checkout Repository Code
        uses: actions/checkout@v6

      - name: Setup | Configure Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25"
          cache: "npm"

      - name: Setup | Install Dependencies
        run: npm ci

      - name: Evaluate | Run Tests
        run: npm run test:coverage -- --ci --runInBand --verbose
